# Generated by Django 6.0.4 on 2026-04-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('quantity_needed', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity needed in KG', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='farmers.croplisting')),
                ('exporter', models.ForeignKey(limit_choices_to={'role': 'exporter'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='inquiries.inquiry')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inquiry Replies',
                'db_table': 'inquiry_replies',
                'ordering': ['created_at'],
            },
        ),
    ]
