# Generated by Django 6.0.4 on 2026-04-25 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(blank=True, help_text='Name in Bangla/local language', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('season', models.CharField(choices=[('kharif1', 'Kharif-1 (Mar–Jun)'), ('kharif2', 'Kharif-2 (Jul–Oct)'), ('rabi', 'Rabi (Nov–Feb)'), ('year_round', 'Year Round')], default='rabi', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vegetables/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vegetables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Quantity in KG', max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='Price per KG in BDT', max_digits=8)),
                ('district', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('kharif1', 'Kharif-1 (Mar–Jun)'), ('kharif2', 'Kharif-2 (Jul–Oct)'), ('rabi', 'Rabi (Nov–Feb)'), ('year_round', 'Year Round')], max_length=20)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold Out'), ('upcoming', 'Upcoming')], default='available', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='crop_listings', to=settings.AUTH_USER_MODEL)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farmers.vegetable')),
            ],
            options={
                'db_table': 'crop_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
