# Generated by Django 6.0.4 on 2026-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='demand_score',
            field=models.FloatField(default=0.5),
        ),
    ]
